import { CSSProperties, StyleRules } from './withStyles.d.ts';
import { AppBarClassKey } from '../AppBar.d.ts';
import { AvatarClassKey } from '../Avatar.d.ts';
import { BackdropClassKey } from '../Backdrop.d.ts';
import { BadgeClassKey } from '../Badge.d.ts';
import { BottomNavigationActionClassKey } from '../BottomNavigationAction.d.ts';
import { BottomNavigationClassKey } from '../BottomNavigation.d.ts';
import { BreadcrumbsClassKey } from '../Breadcrumbs.d.ts';
import { ButtonBaseClassKey } from '../ButtonBase.d.ts';
import { ButtonClassKey } from '../Button.d.ts';
import { ButtonGroupClassKey } from '../ButtonGroup.d.ts';
import { CardActionAreaClassKey } from '../CardActionArea.d.ts';
import { CardActionsClassKey } from '../CardActions.d.ts';
import { CardClassKey } from '../Card.d.ts';
import { CardContentClassKey } from '../CardContent.d.ts';
import { CardHeaderClassKey } from '../CardHeader.d.ts';
import { CardMediaClassKey } from '../CardMedia.d.ts';
import { CheckboxClassKey } from '../Checkbox.d.ts';
import { ChipClassKey } from '../Chip.d.ts';
import { CircularProgressClassKey } from '../CircularProgress.d.ts';
import { CollapseClassKey } from '../Collapse.d.ts';
import { ContainerClassKey } from '../Container.d.ts';
import { DialogActionsClassKey } from '../DialogActions.d.ts';
import { DialogClassKey } from '../Dialog.d.ts';
import { DialogContentClassKey } from '../DialogContent.d.ts';
import { DialogContentTextClassKey } from '../DialogContentText.d.ts';
import { DialogTitleClassKey } from '../DialogTitle.d.ts';
import { DividerClassKey } from '../Divider.d.ts';
import { DrawerClassKey } from '../Drawer.d.ts';
import { ExpansionPanelActionsClassKey } from '../ExpansionPanelActions.d.ts';
import { ExpansionPanelClassKey } from '../ExpansionPanel.d.ts';
import { ExpansionPanelDetailsClassKey } from '../ExpansionPanelDetails.d.ts';
import { ExpansionPanelSummaryClassKey } from '../ExpansionPanelSummary.d.ts';
import { FabClassKey } from '../Fab.d.ts';
import { FilledInputClassKey } from '../FilledInput.d.ts';
import { FormControlClassKey } from '../FormControl.d.ts';
import { FormControlLabelClassKey } from '../FormControlLabel.d.ts';
import { FormGroupClassKey } from '../FormGroup.d.ts';
import { FormHelperTextClassKey } from '../FormHelperText.d.ts';
import { FormLabelClassKey } from '../FormLabel.d.ts';
import { GridClassKey } from '../Grid.d.ts';
import { GridListClassKey } from '../GridList.d.ts';
import { GridListTileBarClassKey } from '../GridListTileBar.d.ts';
import { GridListTileClassKey } from '../GridListTile.d.ts';
import { IconButtonClassKey } from '../IconButton.d.ts';
import { IconClassKey } from '../Icon.d.ts';
import { InputAdornmentClassKey } from '../InputAdornment.d.ts';
import { InputBaseClassKey } from '../InputBase.d.ts';
import { InputClassKey } from '../Input.d.ts';
import { InputLabelClassKey } from '../InputLabel.d.ts';
import { LinearProgressClassKey } from '../LinearProgress.d.ts';
import { LinkClassKey } from '../Link.d.ts';
import { ListClassKey } from '../List.d.ts';
import { ListItemAvatarClassKey } from '../ListItemAvatar.d.ts';
import { ListItemClassKey } from '../ListItem.d.ts';
import { ListItemIconClassKey } from '../ListItemIcon.d.ts';
import { ListItemSecondaryActionClassKey } from '../ListItemSecondaryAction.d.ts';
import { ListItemTextClassKey } from '../ListItemText.d.ts';
import { ListSubheaderClassKey } from '../ListSubheader.d.ts';
import { MenuClassKey } from '../Menu.d.ts';
import { MenuItemClassKey } from '../MenuItem.d.ts';
import { MobileStepperClassKey } from '../MobileStepper.d.ts';
import { NativeSelectClassKey } from '../NativeSelect.d.ts';
import { OutlinedInputClassKey } from '../OutlinedInput.d.ts';
import { PaperClassKey } from '../Paper.d.ts';
import { PopoverClassKey } from '../Popover.d.ts';
import { RadioClassKey } from '../Radio.d.ts';
import { ScopedCssBaselineClassKey } from '../ScopedCssBaseline.d.ts';
import { SelectClassKey } from '../Select.d.ts';
import { SliderClassKey } from '../Slider.d.ts';
import { SnackbarClassKey } from '../Snackbar.d.ts';
import { SnackbarContentClassKey } from '../SnackbarContent.d.ts';
import { StepButtonClasskey } from '../StepButton.d.ts';
import { StepClasskey } from '../Step.d.ts';
import { StepConnectorClasskey } from '../StepConnector.d.ts';
import { StepContentClasskey } from '../StepContent.d.ts';
import { StepIconClasskey } from '../StepIcon.d.ts';
import { StepLabelClasskey } from '../StepLabel.d.ts';
import { StepperClasskey } from '../Stepper.d.ts';
import { SvgIconClassKey } from '../SvgIcon.d.ts';
import { SwitchClassKey } from '../Switch.d.ts';
import { TabClassKey } from '../Tab.d.ts';
import { TableBodyClassKey } from '../TableBody.d.ts';
import { TableCellClassKey } from '../TableCell.d.ts';
import { TableClassKey } from '../Table.d.ts';
import { TableContainerClassKey } from '../TableContainer.d.ts';
import { TableFooterClassKey } from '../TableFooter.d.ts';
import { TableHeadClassKey } from '../TableHead.d.ts';
import { TablePaginationClassKey } from '../TablePagination.d.ts';
import { TableRowClassKey } from '../TableRow.d.ts';
import { TableSortLabelClassKey } from '../TableSortLabel.d.ts';
import { TabsClassKey } from '../Tabs.d.ts';
import { TextFieldClassKey } from '../TextField.d.ts';
import { ToolbarClassKey } from '../Toolbar.d.ts';
import { TooltipClassKey } from '../Tooltip.d.ts';
import { TouchRippleClassKey } from '../ButtonBase/TouchRipple.d.ts';
import { TypographyClassKey } from '../Typography.d.ts';

export type Overrides = {
  [Name in keyof ComponentNameToClassKey]?: Partial<StyleRules<ComponentNameToClassKey[Name]>>;
} & {
  MuiCssBaseline?: {
    '@global'?: {
      '@font-face'?: CSSProperties['@font-face'];
    } & Record<string, CSSProperties['@font-face'] | CSSProperties>; // allow arbitrary selectors
  };
};

export interface ComponentNameToClassKey {
  MuiAppBar: AppBarClassKey;
  MuiAvatar: AvatarClassKey;
  MuiBackdrop: BackdropClassKey;
  MuiBadge: BadgeClassKey;
  MuiBottomNavigation: BottomNavigationClassKey;
  MuiBottomNavigationAction: BottomNavigationActionClassKey;
  MuiBreadcrumbs: BreadcrumbsClassKey;
  MuiButton: ButtonClassKey;
  MuiButtonBase: ButtonBaseClassKey;
  MuiButtonGroup: ButtonGroupClassKey;
  MuiCard: CardClassKey;
  MuiCardActionArea: CardActionAreaClassKey;
  MuiCardActions: CardActionsClassKey;
  MuiCardContent: CardContentClassKey;
  MuiCardHeader: CardHeaderClassKey;
  MuiCardMedia: CardMediaClassKey;
  MuiCheckbox: CheckboxClassKey;
  MuiChip: ChipClassKey;
  MuiCircularProgress: CircularProgressClassKey;
  MuiCollapse: CollapseClassKey;
  MuiContainer: ContainerClassKey;
  /**
   * @deprecated See CssBaseline.d.ts
   */
  MuiCssBaseline: '@global';
  MuiDialog: DialogClassKey;
  MuiDialogActions: DialogActionsClassKey;
  MuiDialogContent: DialogContentClassKey;
  MuiDialogContentText: DialogContentTextClassKey;
  MuiDialogTitle: DialogTitleClassKey;
  MuiDivider: DividerClassKey;
  MuiDrawer: DrawerClassKey;
  MuiExpansionPanel: ExpansionPanelClassKey;
  MuiExpansionPanelActions: ExpansionPanelActionsClassKey;
  MuiExpansionPanelDetails: ExpansionPanelDetailsClassKey;
  MuiExpansionPanelSummary: ExpansionPanelSummaryClassKey;
  MuiFab: FabClassKey;
  MuiFilledInput: FilledInputClassKey;
  MuiFormControl: FormControlClassKey;
  MuiFormControlLabel: FormControlLabelClassKey;
  MuiFormGroup: FormGroupClassKey;
  MuiFormHelperText: FormHelperTextClassKey;
  MuiFormLabel: FormLabelClassKey;
  MuiGrid: GridClassKey;
  MuiGridList: GridListClassKey;
  MuiGridListTile: GridListTileClassKey;
  MuiGridListTileBar: GridListTileBarClassKey;
  MuiIcon: IconClassKey;
  MuiIconButton: IconButtonClassKey;
  MuiInput: InputClassKey;
  MuiInputAdornment: InputAdornmentClassKey;
  MuiInputBase: InputBaseClassKey;
  MuiInputLabel: InputLabelClassKey;
  MuiLinearProgress: LinearProgressClassKey;
  MuiLink: LinkClassKey;
  MuiList: ListClassKey;
  MuiListItem: ListItemClassKey;
  MuiListItemAvatar: ListItemAvatarClassKey;
  MuiListItemIcon: ListItemIconClassKey;
  MuiListItemSecondaryAction: ListItemSecondaryActionClassKey;
  MuiListItemText: ListItemTextClassKey;
  MuiListSubheader: ListSubheaderClassKey;
  MuiMenu: MenuClassKey;
  MuiMenuItem: MenuItemClassKey;
  MuiMobileStepper: MobileStepperClassKey;
  MuiNativeSelect: NativeSelectClassKey;
  MuiOutlinedInput: OutlinedInputClassKey;
  MuiPaper: PaperClassKey;
  MuiPopover: PopoverClassKey;
  MuiRadio: RadioClassKey;
  MuiScopedCssBaseline: ScopedCssBaselineClassKey;
  MuiSelect: SelectClassKey;
  MuiSlider: SliderClassKey;
  MuiSnackbar: SnackbarClassKey;
  MuiSnackbarContent: SnackbarContentClassKey;
  MuiStep: StepClasskey;
  MuiStepButton: StepButtonClasskey;
  MuiStepConnector: StepConnectorClasskey;
  MuiStepContent: StepContentClasskey;
  MuiStepIcon: StepIconClasskey;
  MuiStepLabel: StepLabelClasskey;
  MuiStepper: StepperClasskey;
  MuiSvgIcon: SvgIconClassKey;
  MuiSwitch: SwitchClassKey;
  MuiTab: TabClassKey;
  MuiTable: TableClassKey;
  MuiTableBody: TableBodyClassKey;
  MuiTableCell: TableCellClassKey;
  MuiTableContainer: TableContainerClassKey;
  MuiTableFooter: TableFooterClassKey;
  MuiTableHead: TableHeadClassKey;
  MuiTablePagination: TablePaginationClassKey;
  MuiTableRow: TableRowClassKey;
  MuiTableSortLabel: TableSortLabelClassKey;
  MuiTabs: TabsClassKey;
  MuiTextField: TextFieldClassKey;
  MuiToolbar: ToolbarClassKey;
  MuiTooltip: TooltipClassKey;
  MuiTouchRipple: TouchRippleClassKey;
  MuiTypography: TypographyClassKey;
}
