import { AppBarProps } from '../AppBar.d.ts';
import { AvatarProps } from '../Avatar.d.ts';
import { BackdropProps } from '../Backdrop.d.ts';
import { BadgeProps } from '../Badge.d.ts';
import { BottomNavigationActionProps } from '../BottomNavigationAction.d.ts';
import { BottomNavigationProps } from '../BottomNavigation.d.ts';
import { BreadcrumbsProps } from '../Breadcrumbs.d.ts';
import { ButtonBaseProps } from '../ButtonBase.d.ts';
import { ButtonGroupProps } from '../ButtonGroup.d.ts';
import { ButtonProps } from '../Button.d.ts';
import { CardActionAreaProps } from '../CardActionArea.d.ts';
import { CardActionsProps } from '../CardActions.d.ts';
import { CardContentProps } from '../CardContent.d.ts';
import { CardHeaderProps } from '../CardHeader.d.ts';
import { CardMediaProps } from '../CardMedia.d.ts';
import { CardProps } from '../Card.d.ts';
import { CheckboxProps } from '../Checkbox.d.ts';
import { ChipProps } from '../Chip.d.ts';
import { CircularProgressProps } from '../CircularProgress.d.ts';
import { CollapseProps } from '../Collapse.d.ts';
import { ContainerProps } from '../Container.d.ts';
import { CssBaselineProps } from '../CssBaseline.d.ts';
import { DialogActionsProps } from '../DialogActions.d.ts';
import { DialogContentProps } from '../DialogContent.d.ts';
import { DialogContentTextProps } from '../DialogContentText.d.ts';
import { DialogProps } from '../Dialog.d.ts';
import { DialogTitleProps } from '../DialogTitle.d.ts';
import { DividerProps } from '../Divider.d.ts';
import { DrawerProps } from '../Drawer.d.ts';
import { ExpansionPanelActionsProps } from '../ExpansionPanelActions.d.ts';
import { ExpansionPanelDetailsProps } from '../ExpansionPanelDetails.d.ts';
import { ExpansionPanelProps } from '../ExpansionPanel.d.ts';
import { ExpansionPanelSummaryProps } from '../ExpansionPanelSummary.d.ts';
import { FabProps } from '../Fab.d.ts';
import { FilledInputProps } from '../FilledInput.d.ts';
import { FormControlLabelProps } from '../FormControlLabel.d.ts';
import { FormControlProps } from '../FormControl.d.ts';
import { FormGroupProps } from '../FormGroup.d.ts';
import { FormHelperTextProps } from '../FormHelperText.d.ts';
import { FormLabelProps } from '../FormLabel.d.ts';
import { GridListProps } from '../GridList.d.ts';
import { GridListTileBarProps } from '../GridListTileBar.d.ts';
import { GridListTileProps } from '../GridListTile.d.ts';
import { GridProps } from '../Grid.d.ts';
import { IconButtonProps } from '../IconButton.d.ts';
import { IconProps } from '../Icon.d.ts';
import { InputAdornmentProps } from '../InputAdornment.d.ts';
import { InputBaseProps } from '../InputBase.d.ts';
import { InputLabelProps } from '../InputLabel.d.ts';
import { InputProps } from '../Input.d.ts';
import { LinearProgressProps } from '../LinearProgress.d.ts';
import { LinkProps } from '../Link.d.ts';
import { ListItemAvatarProps } from '../ListItemAvatar.d.ts';
import { ListItemIconProps } from '../ListItemIcon.d.ts';
import { ListItemProps } from '../ListItem.d.ts';
import { ListItemSecondaryActionProps } from '../ListItemSecondaryAction.d.ts';
import { ListItemTextProps } from '../ListItemText.d.ts';
import { ListProps } from '../List.d.ts';
import { ListSubheaderProps } from '../ListSubheader.d.ts';
import { MenuItemProps } from '../MenuItem.d.ts';
import { MenuListProps } from '../MenuList.d.ts';
import { MenuProps } from '../Menu.d.ts';
import { MobileStepperProps } from '../MobileStepper.d.ts';
import { ModalProps } from '../Modal.d.ts';
import { NativeSelectProps } from '../NativeSelect.d.ts';
import { Options as useMediaQueryOptions } from '../useMediaQuery.d.ts';
import { OutlinedInputProps } from '../OutlinedInput.d.ts';
import { PaperProps } from '../Paper.d.ts';
import { PopoverProps } from '../Popover.d.ts';
import { RadioGroupProps } from '../RadioGroup.d.ts';
import { RadioProps } from '../Radio.d.ts';
import { SelectProps } from '../Select.d.ts';
import { SliderProps } from '../Slider.d.ts';
import { SnackbarContentProps } from '../SnackbarContent.d.ts';
import { SnackbarProps } from '../Snackbar.d.ts';
import { StepButtonProps } from '../StepButton.d.ts';
import { StepConnectorProps } from '../StepConnector.d.ts';
import { StepContentProps } from '../StepContent.d.ts';
import { StepIconProps } from '../StepIcon.d.ts';
import { StepLabelProps } from '../StepLabel.d.ts';
import { StepperProps } from '../Stepper.d.ts';
import { StepProps } from '../Step.d.ts';
import { SvgIconProps } from '../SvgIcon.d.ts';
import { SwipeableDrawerProps } from '../SwipeableDrawer.d.ts';
import { SwitchProps } from '../Switch.d.ts';
import { TableBodyProps } from '../TableBody.d.ts';
import { TableCellProps } from '../TableCell.d.ts';
import { TableContainerProps } from '../TableContainer.d.ts';
import { TableHeadProps } from '../TableHead.d.ts';
import { TablePaginationProps } from '../TablePagination.d.ts';
import { TableProps } from '../Table.d.ts';
import { TableRowProps } from '../TableRow.d.ts';
import { TableSortLabelProps } from '../TableSortLabel.d.ts';
import { TabProps } from '../Tab.d.ts';
import { TabsProps } from '../Tabs.d.ts';
import { TextFieldProps } from '../TextField.d.ts';
import { ToolbarProps } from '../Toolbar.d.ts';
import { TooltipProps } from '../Tooltip.d.ts';
import { TouchRippleProps } from '../ButtonBase/TouchRipple.d.ts';
import { TypographyProps } from '../Typography.d.ts';
import { WithWidthOptions } from '../withWidth.d.ts';

export type ComponentsProps = {
  [Name in keyof ComponentsPropsList]?: Partial<ComponentsPropsList[Name]>;
};

export interface ComponentsPropsList {
  MuiAppBar: AppBarProps;
  MuiAvatar: AvatarProps;
  MuiBackdrop: BackdropProps;
  MuiBadge: BadgeProps;
  MuiBottomNavigation: BottomNavigationProps;
  MuiBottomNavigationAction: BottomNavigationActionProps;
  MuiBreadcrumbs: BreadcrumbsProps;
  MuiButton: ButtonProps;
  MuiButtonBase: ButtonBaseProps;
  MuiButtonGroup: ButtonGroupProps;
  MuiCard: CardProps;
  MuiCardActionArea: CardActionAreaProps;
  MuiCardActions: CardActionsProps;
  MuiCardContent: CardContentProps;
  MuiCardHeader: CardHeaderProps;
  MuiCardMedia: CardMediaProps;
  MuiCheckbox: CheckboxProps;
  MuiChip: ChipProps;
  MuiCircularProgress: CircularProgressProps;
  MuiCollapse: CollapseProps;
  MuiContainer: ContainerProps;
  MuiCssBaseline: CssBaselineProps;
  MuiDialog: DialogProps;
  MuiDialogActions: DialogActionsProps;
  MuiDialogContent: DialogContentProps;
  MuiDialogContentText: DialogContentTextProps;
  MuiDialogTitle: DialogTitleProps;
  MuiDivider: DividerProps;
  MuiDrawer: DrawerProps;
  MuiExpansionPanel: ExpansionPanelProps;
  MuiExpansionPanelActions: ExpansionPanelActionsProps;
  MuiExpansionPanelDetails: ExpansionPanelDetailsProps;
  MuiExpansionPanelSummary: ExpansionPanelSummaryProps;
  MuiFab: FabProps;
  MuiFilledInput: FilledInputProps;
  MuiFormControl: FormControlProps;
  MuiFormControlLabel: FormControlLabelProps;
  MuiFormGroup: FormGroupProps;
  MuiFormHelperText: FormHelperTextProps;
  MuiFormLabel: FormLabelProps;
  MuiGrid: GridProps;
  MuiGridList: GridListProps;
  MuiGridListTile: GridListTileProps;
  MuiGridListTileBar: GridListTileBarProps;
  MuiIcon: IconProps;
  MuiIconButton: IconButtonProps;
  MuiInput: InputProps;
  MuiInputAdornment: InputAdornmentProps;
  MuiInputBase: InputBaseProps;
  MuiInputLabel: InputLabelProps;
  MuiLinearProgress: LinearProgressProps;
  MuiLink: LinkProps;
  MuiList: ListProps;
  MuiListItem: ListItemProps;
  MuiListItemAvatar: ListItemAvatarProps;
  MuiListItemIcon: ListItemIconProps;
  MuiListItemSecondaryAction: ListItemSecondaryActionProps;
  MuiListItemText: ListItemTextProps;
  MuiListSubheader: ListSubheaderProps;
  MuiMenu: MenuProps;
  MuiMenuItem: MenuItemProps;
  MuiMenuList: MenuListProps;
  MuiMobileStepper: MobileStepperProps;
  MuiModal: ModalProps;
  MuiNativeSelect: NativeSelectProps;
  MuiOutlinedInput: OutlinedInputProps;
  MuiPaper: PaperProps;
  MuiPopover: PopoverProps;
  MuiRadio: RadioProps;
  MuiRadioGroup: RadioGroupProps;
  MuiSelect: SelectProps;
  MuiSlider: SliderProps;
  MuiSnackbar: SnackbarProps;
  MuiSnackbarContent: SnackbarContentProps;
  MuiStep: StepProps;
  MuiStepButton: StepButtonProps;
  MuiStepConnector: StepConnectorProps;
  MuiStepContent: StepContentProps;
  MuiStepIcon: StepIconProps;
  MuiStepLabel: StepLabelProps;
  MuiStepper: StepperProps;
  MuiSvgIcon: SvgIconProps;
  MuiSwipeableDrawer: SwipeableDrawerProps;
  MuiSwitch: SwitchProps;
  MuiTab: TabProps;
  MuiTable: TableProps;
  MuiTableBody: TableBodyProps;
  MuiTableCell: TableCellProps;
  MuiTableContainer: TableContainerProps;
  MuiTableHead: TableHeadProps;
  MuiTablePagination: TablePaginationProps;
  MuiTableRow: TableRowProps;
  MuiTableSortLabel: TableSortLabelProps;
  MuiTabs: TabsProps;
  MuiTextField: TextFieldProps;
  MuiToolbar: ToolbarProps;
  MuiTooltip: TooltipProps;
  MuiTouchRipple: TouchRippleProps;
  MuiTypography: TypographyProps;
  MuiUseMediaQuery: useMediaQueryOptions;
  MuiWithWidth: WithWidthOptions;
}
